### ISSUE TITLE
Use `argparse`

### ISSUE THREAD

**Issue by jnothman** [sigmavirus24/github-cli#12]
Currently your argument parsing is very quirky. Using `gh issues` (which is what's in your readme) instead of `gh issue` silently fails. The validation offered by `argparse.ArgumentParser.add_subparsers` is so completely worth your while.

**Comment by sigmavirus24** [comment]
Yeah, this tool will be getting a lot of TLC after tomorrow. I think I'm going to more closely inspect `argparse` in spite of my desire to have as few dependencies as possible. Optparse is a pain. I'm also thinking of doing yet another redesign of the how the tool works to a degree. I'm not happy with a few pieces of it as is.

Feel free to start a pull request with the migration to `argparse` if you have the desire/time.
