### ISSUE TITLE
Good idea but how is this different?

### ISSUE THREAD

**Issue by vinitkumar** [sigmavirus24/github-cli#3]
Check this out https://github.com/myusuf3/octogit 
This already provides all the functionality, how is your different?

**Comment by sigmavirus24** [comment]
The intended design is to not throw you back into a browser to do simple tasks like creating, responding to, closing or reopening an issue. The work has entirely stalled, but the intent was a real command line interface and not half of one. Also the plan is to absorb some of hub's functionality (i.e. turning an issue into a pull request). Honestly though I haven't kept up with octogit and have little awareness of any new features it provides.

**Comment by vinitkumar** [comment]
Cool that you trying to get that functionality into command-line. Though some awareness from a similar project will prevent you from reinventing the wheel. Since both of these projects are based on python. Anyways, keep up the good work man.
Best Wishes, 
Vinit

**Comment by sigmavirus24** [comment]
Well the other issue is that octogit is performing the API calls directly while I'm choosing to use my own github3.py library. I'm also using an entirely different design to the tool ad I'm mostly doing this for fun as well (as I did todo.py) so I have no issue with reinventing the wheel. Besides competition is always a good thing. It makes all such products better.

Feel free to contribute though if you want to see features here that don't exist in octogit.

Thanks,
Ian

P.S. More specifics can be found in the design documentation at the top level of the repo.

**Comment by sigmavirus24** [comment]
@vinitcool76 feel free to try it out as there's now a beta on pip
